### ISSUE TITLE
Document team roles and resources

### ISSUE THREAD

**Issue by eugene-chow** [CloudCommandos/admin#1]
- [x] Fill up this `admin` repo with documents related to team ops
- [x] Create `champions.md` document with a table listing your duties. Each of you will be champions for various duties. In ESTL, we call this `DRI` or Directly Responsible Individual but I think it sounds clinical.
   1. John: Team Lead, Github CloudComandos admin
   1. Alex: Call for weekly status update and monthly meetups
   1. Young Ee: Documentation guru, Procurement matters
- [x] Create `team-resources.md` document to list the resources used by the team. If there's anything that you deem useful, please add to the list.
   1. Github
   1. Google calendar: Alex please create one for the team since you're in charge of scheduling
   1. 1Password/LastPass: I strongly suggest using a password manager but for the team to share credentials, you need to pay for it. For now you can setup individual accounts.

**Comment by youngee91** [comment]
Tasks completed. Apologies for the delay.

**Comment by eugene-chow** [comment]
@youngee91 how this works is that you check off the list above then close this issue. @CloudCommandos/infra please take note.

**Comment by youngee91** [comment]
@eugene-chow I am unable to check off the list. Need admin privileges to check off the issue

**Comment by eugene-chow** [comment]
Try again. I've given you permissions.
