### ISSUE TITLE
Schedule 1-on-1s

### ISSUE THREAD

**Issue by eugene-chow** [CloudCommandos/admin#5]
In the team calendar, please schedule a 1-on-1 every 2 months for each of the 3 musketeers and also a monthly f2f team meeting. If it clashes with my schedule, I'll shift it accordingly.

@CloudCommandos/infra put your away dates (vacation, ICT, etc) in the calendar.

Also, document the above in `team-sop.md` in this repo.

Thanks!

**Comment by alexling92** [comment]
Created the sop file. 1-on-1 session will be personally updated by each individual on the CC's calendar.
As for the team meeting, I will update the calendar once everyone is okay with the date.

**Comment by eugene-chow** [comment]
Thanks! Once you're done, remember to close the issue.

**Comment by alexling92** [comment]
Alright!

**Comment by eugene-chow** [comment]
I haven't received calendar invites for the 1-on-1s and team meetings. If it's not yet created, the issue should remain open until the task is done.

**Comment by alexling92** [comment]
Okay. I will close this issue once the calendar is updated.
May i also ask if we can just plot in the schedule for the meeting, or should we consult you to arrange a suitable date?

**Comment by eugene-chow** [comment]
I’m mostly available in the upcoming months so just schedule a date. If I cannot make it closer to the date, I’ll shift the meeting accordingly.

**Comment by alexling92** [comment]
Hi Eugene, we have updated the calendar with our individual meeting with you. Do take note that we have also shifted the date for the team meeting.
I will close this issue since all the tasks have been completed.
