### ISSUE TITLE
Start a Medium account

### ISSUE THREAD

**Issue by eugene-chow** [CloudCommandos/admin#6]
Setup a Medium account, create a publication (@CloudCommandos/infra you guys collectively decide the name) and invite everyone to be an owner (or is it editor?). The rationale for this is:
1. Hone your writing skills. When you become bosses yourselves, writing skills will help you sell your ideas much better.
1. Expose your unit to the public so that your bosses are aware of what your work, your peers can see what you do, and hopefully ppl will want to join the team because you're doing awesome work.
1. Boost your resume portfolio. Industry headhunters look at the opensource work you have done.

For starters, you can just post a rehash of your email server documentation. I understand that writing is brain-intensive but after a few articles, it will become natural to you.

Also, now is really the best time to practise because you guys are undergoing BMT. Once you guys turn ops, you'll have little time to write. Do it while you're young :)

**Comment by youngee91** [comment]
I have setup an Medium Account. Here's the link to our Medium account: https://medium.com/minds-in-the-cloud/

I have invited John and Alex as the editor as well. We will update promptly

**Comment by eugene-chow** [comment]
Awesome! Looking forward to writeups :)
