### ISSUE TITLE
Schedule 1:1s until end of 2019

### ISSUE THREAD

**Issue by eugene-chow** [CloudCommandos/admin#7]
Please schedule the following using repeating events in Google Calendar
- [x] 10-weekly 1:1s until the end of 2019
- [x] Monthly team meetings

Thanks!

@CloudCommandos/infra Please take note of the updates to the [Champions list](https://github.com/CloudCommandos/admin/blob/master/champions.md)

**Comment by eugene-chow** [comment]
@youngee91 Sorry I missed out the frequency of the scheduling. Please see the OP and check off the list when you've done it. Thanks!

**Comment by youngee91** [comment]
@eugene-chow I have scheduled the respective meetings on google calendar. Please have a look and let me know if there is any issue. Thanks!

**Comment by eugene-chow** [comment]
LGTM. Thanks!
